name: flutter_starter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  provider: ^6.1.2
  jwt_decoder: ^2.0.1
  bootstrap_icons: ^1.11.3
  cupertino_icons: ^1.0.6
  fl_chart: ^0.67.0
  intl: ^0.19.0
  http_parser: ^4.0.2
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
